project:
  type: website
  output-dir: ../docs
  resources:
    - .nojekyll

execute:
  freeze: auto

filters:
  - diagrams

website:
  title: "quarto-diagrams"
  navbar:
    left:
      - text: "Get Started"
        href: index.qmd
      - text: "Styles"
        menu:
          - text: "Circle Flow"
            href: circle-flow.qmd
          - text: "Pie"
            href: pie.qmd
          - text: "Process"
            href: process.qmd
          - text: "Pyramid"
            href: pyramid.qmd
          - text: "Matrix"
            href: matrix.qmd
          - text: "Hierarchy"
            href: hierarchy.qmd
          - text: "Venn"
            href: venn.qmd
          - text: "Stacked Venn"
            href: stacked-venn.qmd
          - text: "Funnel"
            href: funnel.qmd
          - text: "Cycle"
            href: cycle.qmd
      - text: "Concepts"
        menu:
          - text: "Node Shapes"
            href: node-shapes.qmd
          - text: "Arrow Types"
            href: arrow-types.qmd
          - text: "Colors"
            href: colors.qmd
          - text: "Annotations"
            href: annotations.qmd
          - text: "Customization"
            href: customization.qmd
    right:
      - icon: github
        href: https://github.com/EmilHvitfeldt/quarto-diagrams
        aria-label: GitHub

format:
  html:
    toc: true
    toc-depth: 2
    css: styles.css
